### ISSUE TITLE
sysmon installer with extra quotes

### ISSUE THREAD

**Issue by cowbe0x004** [freeload101/SCRIPTS#2]
Seems like you have extra quotes at the end of @powershell lines, for example,

`@powershell (new-object System.Net.WebClient).DownloadFile('https://live.sysinternals.com/Sysmon64.exe','C:\ProgramData\sysmon\sysmon64.exe')"`

That quote doesn't give me error when I run the script so sorry if this is syntactically correct.

**Comment by freeload101** [comment]
Hah it works not sure how/why it still works but ill update it seems like I can remove all the double quotes... Thanks!
